language: node_js
node_js:
- '10'
deploy:
  provider: npm
  email: teodor.ivanov92@gmail.com
  on:
    repo: strictr/markdown-lint-config
    branch: master
  api_key:
    secure: NLcHkykuhMAnkXPG8y9Z1eTDbL6Cg22x8fsbsBMDthiuWY+dQ8mISiGzJr4FtsxZeiuRxf4fQUnvn5P7+nfQqo6HnjT0e1Vdz6rQQPPFnOzooRfZAmZ2XGVMbJxULhQisRZrBPvwAdpljSfpObTkT3trlGKf/2M43XTNUov2D404vBbEyiCLluFfSbTArqF9Pxoboh+W5X4FyHaBL/M+3/qUhFQXnOsYRLVj3t9LVRBm7rg6dcv5/WWLqst3xgMBX62G8c0Uh9cKTgsORpPMh5VGfaTV78VmwYUVBTcFHn+HZ4xGhU8SXVwspwPUvUNDPmkRHwHArj5SXujKMrEVrvLpFp/4y7iMxPFFvomH3MGOUw96de/x9g3kZyUVhxNhRMt9Dbjo7tNb596bQgBYyFLpbYs/dJgEj9hyUw+UUjZMo7oE8kwJy9StP6AfdffQJjFgvog8JrJQVyZ0Z7aVY1/LMWNLm3xdNzsqu648sqes0b5PoWLdoch/2DD6sT2gUc5PMImTuxW+GdAOxRgjiTH1k57nSuh/lD8VbvONcwEKCGXs88Ez3NUEmlvP3C1eXocoqoMjVUFANz9yoIXiosIFIjx/lm8clbKNKnnijMyTmowvvmM3mvEti6G6m/wzUtXWr9LrAdfjoxi72g0cU3rksHAbIlc3UJkzgkivRMk=
